version: '3.9'

services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=security